### ISSUE TITLE
大佬，这个报错是什么意思啊

### ISSUE THREAD

**Issue by F0reseee** [liuzhijie443/ZhiMiao_JiuJia#1]
![微信截图_20220620214213](https://user-images.githubusercontent.com/105440986/174614796-b4e3174b-d8dc-485d-9a88-78e9e7a89a27.png)

**Comment by liuzhijie443** [comment]
> ![微信截图_20220620214213](https://user-images.githubusercontent.com/105440986/174614796-b4e3174b-d8dc-485d-9a88-78e9e7a89a27.png)

Max retries exceeded with url，自己上网搜一下
