### ISSUE TITLE
有遇到过返回状态为408的问题吗

### ISSUE THREAD

**Issue by wjllp** [liuzhijie443/ZhiMiao_JiuJia#14]
前面几个接口都能跑通，加解密也没啥问题，到最后一个提交预约的接口时，返回{"status": 408}

**Comment by cyrusliu1984** [comment]
您好，请问您解决问题了吗？我在调试时碰到了与您一样的问题~

**Comment by wjllp** [comment]
解决了，408是cookie不对。
我是手机上抓包，电脑上跑的，连的公司的Wi-Fi，手机和电脑的公网IP不一致导致的。
电脑上抓安卓模拟器的包然后在电脑上跑就可以了，不过这个小程序最近更新优化了一版，这个脚本已经不适用了，需要小改一下才行
