### ISSUE TITLE
来帮帮弟弟 ，在作者基础上，增加了获取 pid的代码  但遇到了新的问题

### ISSUE THREAD

**Issue by Zhu-HH** [liuzhijie443/ZhiMiao_JiuJia#24]
增加了获取pid的请求之后，测试可以正常获取到id信息。

但进行第二天整点获取pid时，却获取不到，也就是早上9.00发送请求来获取pid，获取不到，代码做了处理，获取不到pid 就继续发送请求，结果 第二次到了9h00min03s 才返回结果，这次获取到pid信息，但此时已经疫苗没了。有没有好兄弟  推荐推荐 将代码改成 协程好呢还是 改成 多线程好。或者用其他框架 不用requests框架来发送请求，

导致上述的问题  是 我的网络问题，还是 代码问题  还是 服务器的问题呢？ 毕竟是 整点发送的请求，而回来的response 却没有id信息

小弟是萌新宝宝，各位大佬给个意见

**Comment by evasbdx** [comment]
大佬，实时获取pid的代码搞定了吗？我的也出现了问题

**Comment by Zhu-HH** [comment]
> 大佬，实时获取pid的代码搞定了吗？我的也出现了问题

算不上实时获取pid，我最近地区没有放针，没有测试代码有效性。

上次写的代码顶多是 到整点预约时间了，我发请求，response里面没有pid信息，过了2-3s后才能拿到id信息。结果原作者设置requests的read time out 超时了，刚拿到id信息，进行下一步询问具体日期的时候 readtimeout了。结果就到了requests的最大重试次数。就错失机会。就没进行测试了。

另外，大佬你测试过你的代码整点获取到id是用的哪种方式呀？

**Comment by evasbdx** [comment]
我这边找了几个朋友，一起弄， 现在还没有进展，我们能分享一下双方的代码吗？

**Comment by Zhu-HH** [comment]
> 我这边找了几个朋友，一起弄， 现在还没有进展，我们能分享一下双方的代码吗？
我回老家了，没电脑，代码暂时分享不了。思路都差不多和getdata函数里面的差不多
copy一份getdata函数 ，剩下只处理response 中的json    id信息，加个异常捕获 啥的 代码就好了，没啥技术含量，没涉及到多线程处理。

你那边地区能抢？可以的话 等我有电脑了你把cookie给我，我给你跑一跑，顺便也测试我代码健壮性😏

**Comment by evasbdx** [comment]
我这边刚过，昨天结束了，有了我发给你把，你加我一下吧，我们在qq上聊聊（839208022）
