### ISSUE TITLE
配置应该没问题，就是测试的时候预约不了。

### ISSUE THREAD

**Issue by ati776** [liuzhijie443/ZhiMiao_JiuJia#7]
[jiujia]
cookie=*******
wait_speed=1000
buy_speed=1000
p_id=7
id=1762
出错如下图：
https://i.imgtg.com/2022/07/01/NDnlK.png

**Comment by liuzhijie443** [comment]
> [jiujia] cookie=******* wait_speed=1000 buy_speed=1000 p_id=7 id=1762 出错如下图： https://i.imgtg.com/2022/07/01/NDnlK.png

这是测试的时候吗？还是抢的时候，换个医院的疫苗试试

**Comment by huanghelouzi** [comment]
![image](https://user-images.githubusercontent.com/39337032/180356087-e487bd56-6c34-4f63-a2b5-98b1b9d020bc.png)
您好，我出现这个问题
